trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: "1.9.7"
  AWS_REGION: 'us-east-2'

steps:

# Step 1: Install Terraform manually
- script: |
    sudo apt-get update
    sudo apt-get install -y wget unzip
    wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
    unzip terraform_$(TF_VERSION)_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform --version
  displayName: 'Install Terraform'

# Step 2: Terraform Init
- script: |
    terraform init
  workingDirectory: 'ecs-terraform'
  displayName: '.'

# Step 3: Terraform Plan
- script: |
    terraform plan -out=tfplan -var "aws_region=$(AWS_REGION)"
  workingDirectory: '.'
  displayName: 'Terraform Plan'

# Step 4: Terraform Apply
- script: |
    terraform apply -auto-approve tfplan
  workingDirectory: '.'
  displayName: 'Terraform Apply'
