trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: MyAWSVariables  # name of your variable group
- name: TF_VERSION
  value: "1.9.7"
- name: AWS_REGION
  value: "us-east-2"
- name: AWS_ACCOUNT_ID
  value: "597406702314"

steps:

# Step 1: Install Terraform manually
- script: |
    sudo apt-get update
    sudo apt-get install -y wget unzip
    wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
    unzip terraform_$(TF_VERSION)_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform --version
  displayName: 'Install Terraform'

# Step 2: Set AWS credentials (from pipeline secrets)
- script: |
    export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
    export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
    export AWS_DEFAULT_REGION=$(AWS_REGION)
  displayName: 'Set AWS Credentials'

# Step 3: Terraform Init
- script: |
    terraform init
  workingDirectory: '.'
  displayName: 'Terraform Init'

# Step 4: Terraform Plan
- script: |
    terraform plan -out=tfplan \
      -var "aws_region=$(AWS_REGION)" \
      -var "aws_account_id=$(AWS_ACCOUNT_ID)"
  workingDirectory: '.'
  displayName: 'Terraform Plan'

# Step 5: Terraform Apply
- script: |
    terraform apply -auto-approve tfplan
  workingDirectory: '.'
  displayName: 'Terraform Apply'
