trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: "6.14.1"
  AWS_REGION: 'us-east-2'

steps:

# Step 1: Install Terraform
- task: TerraformInstaller@1
  displayName: 'Install Terraform $(TF_VERSION)'
  inputs:
    terraformVersion: $(TF_VERSION)

# Step 2: Verify Terraform installation
- script: |
    terraform --version
  displayName: 'Verify Terraform CLI'

# Step 3: Terraform Init
- task: TerraformCLI@1
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: 'ecs-terraform'
    environmentServiceNameAWS: 'AWS-Service-Connection'

# Step 4: Terraform Plan
- task: TerraformCLI@1
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: 'ecs-terraform'
    environmentServiceNameAWS: 'AWS-Service-Connection'
    vars: |
      aws_region=$(AWS_REGION)

# Step 5: Terraform Apply
- task: TerraformCLI@1
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    workingDirectory: 'ecs-terraform'
    environmentServiceNameAWS: 'AWS-Service-Connection'
    args: '-auto-approve'
    vars: |
      aws_region=$(AWS_REGION)
